// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
  apiKey: "AIzaSyA09G0lCb123Ptdqz_8jpSHqKB95tEakD0",
  authDomain: "fir-d8dd0.firebaseapp.com",
  projectId: "fir-d8dd0",
  storageBucket: "fir-d8dd0.appspot.com",
  messagingSenderId: "101839629105",
  appId: "1:101839629105:web:d97fc84e41899891469e10",
  measurementId: "G-T1S96HQGEX"
  );

  static const FirebaseOptions ios = FirebaseOptions(
  apiKey: "AIzaSyA09G0lCb123Ptdqz_8jpSHqKB95tEakD0",
  authDomain: "fir-d8dd0.firebaseapp.com",
  projectId: "fir-d8dd0",
  storageBucket: "fir-d8dd0.appspot.com",
  messagingSenderId: "101839629105",
  appId: "1:101839629105:web:d97fc84e41899891469e10",
  measurementId: "G-T1S96HQGEX"
  );
}
